--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2026-04-29 23:20:25

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16625)
-- Name: companie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.companie (
    id integer NOT NULL,
    name character varying(255),
    siteid integer NOT NULL,
    url character varying(255)
);


ALTER TABLE public.companie OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16624)
-- Name: companie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.companie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16634)
-- Name: dosageform; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dosageform (
    id integer NOT NULL,
    imglink character varying(255),
    name character varying(255),
    siteid integer NOT NULL
);


ALTER TABLE public.dosageform OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16633)
-- Name: dosageform_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dosageform ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dosageform_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16600)
-- Name: generics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.generics (
    id integer NOT NULL,
    name character varying(255),
    siteid integer NOT NULL,
    slug character varying(255),
    type character varying(255),
    url character varying(255),
    CONSTRAINT generics_type_check CHECK (((type)::text = ANY ((ARRAY['ALLOPATHIC'::character varying, 'HERBAL'::character varying])::text[])))
);


ALTER TABLE public.generics OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16599)
-- Name: generics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.generics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.generics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16665)
-- Name: medicine; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.medicine (
    id integer NOT NULL,
    name character varying(255),
    packsizeandprice character varying(255),
    siteid integer NOT NULL,
    strength character varying(255),
    url character varying(255),
    companie_id integer,
    dosageform_id integer,
    generics_id integer
);


ALTER TABLE public.medicine OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16664)
-- Name: medicine_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.medicine ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medicine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4762 (class 2606 OID 16631)
-- Name: companie companie_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companie
    ADD CONSTRAINT companie_pkey PRIMARY KEY (id);


--
-- TOC entry 4765 (class 2606 OID 16640)
-- Name: dosageform dosageform_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dosageform
    ADD CONSTRAINT dosageform_pkey PRIMARY KEY (id);


--
-- TOC entry 4759 (class 2606 OID 16607)
-- Name: generics generics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.generics
    ADD CONSTRAINT generics_pkey PRIMARY KEY (id);


--
-- TOC entry 4767 (class 2606 OID 16671)
-- Name: medicine medicine_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medicine
    ADD CONSTRAINT medicine_pkey PRIMARY KEY (id);


--
-- TOC entry 4760 (class 1259 OID 16608)
-- Name: idx_siteid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_siteid ON public.generics USING btree (siteid);


--
-- TOC entry 4763 (class 1259 OID 16632)
-- Name: idx_siteid_companie; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_siteid_companie ON public.companie USING btree (siteid);


--
-- TOC entry 4768 (class 2606 OID 16677)
-- Name: medicine fka7u6e8cuqs0llf2ss7i0cl56e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medicine
    ADD CONSTRAINT fka7u6e8cuqs0llf2ss7i0cl56e FOREIGN KEY (dosageform_id) REFERENCES public.dosageform(id);


--
-- TOC entry 4769 (class 2606 OID 16682)
-- Name: medicine fkjf9svl123d3ggjs70bkqqje50; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medicine
    ADD CONSTRAINT fkjf9svl123d3ggjs70bkqqje50 FOREIGN KEY (generics_id) REFERENCES public.generics(id);


--
-- TOC entry 4770 (class 2606 OID 16672)
-- Name: medicine fkti7dsvuf64qr2jj2hn8cbcfeh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medicine
    ADD CONSTRAINT fkti7dsvuf64qr2jj2hn8cbcfeh FOREIGN KEY (companie_id) REFERENCES public.companie(id);


-- Completed on 2026-04-29 23:20:25

--
-- PostgreSQL database dump complete
--

